/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface GelatoResolverV2Interface extends utils.Interface {
  functions: {
    "ETH()": FunctionFragment;
    "checkerStopStream(address,bool,uint8)": FunctionFragment;
    "checkerwithdrawStep(address)": FunctionFragment;
    "createStopStreamTimedTask(address,uint256,bool,uint8)": FunctionFragment;
    "createWithdraStepTask(address,uint256)": FunctionFragment;
    "initialize(address,address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "ETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "checkerStopStream",
    values: [string, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkerwithdrawStep",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "createStopStreamTimedTask",
    values: [string, BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createWithdraStepTask",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "ETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkerStopStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkerwithdrawStep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createStopStreamTimedTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createWithdraStepTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;

  events: {
    "Initialized(uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
}

export type InitializedEvent = TypedEvent<[number], { version: number }>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface GelatoResolverV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GelatoResolverV2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ETH(overrides?: CallOverrides): Promise<[string]>;

    checkerStopStream(
      _receiver: string,
      _all: boolean,
      _flowType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { canExec: boolean; execPayload: string }>;

    checkerwithdrawStep(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createStopStreamTimedTask(
      _supplier: string,
      _stopDateInMs: BigNumberish,
      _all: boolean,
      _flowType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createWithdraStepTask(
      _supplier: string,
      _stepTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialize(
      _ops: string,
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  ETH(overrides?: CallOverrides): Promise<string>;

  checkerStopStream(
    _receiver: string,
    _all: boolean,
    _flowType: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[boolean, string] & { canExec: boolean; execPayload: string }>;

  checkerwithdrawStep(
    _receiver: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createStopStreamTimedTask(
    _supplier: string,
    _stopDateInMs: BigNumberish,
    _all: boolean,
    _flowType: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createWithdraStepTask(
    _supplier: string,
    _stepTime: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialize(
    _ops: string,
    _pool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    ETH(overrides?: CallOverrides): Promise<string>;

    checkerStopStream(
      _receiver: string,
      _all: boolean,
      _flowType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { canExec: boolean; execPayload: string }>;

    checkerwithdrawStep(
      _receiver: string,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { canExec: boolean; execPayload: string }>;

    createStopStreamTimedTask(
      _supplier: string,
      _stopDateInMs: BigNumberish,
      _all: boolean,
      _flowType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    createWithdraStepTask(
      _supplier: string,
      _stepTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    initialize(
      _ops: string,
      _pool: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;
  };

  estimateGas: {
    ETH(overrides?: CallOverrides): Promise<BigNumber>;

    checkerStopStream(
      _receiver: string,
      _all: boolean,
      _flowType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkerwithdrawStep(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createStopStreamTimedTask(
      _supplier: string,
      _stopDateInMs: BigNumberish,
      _all: boolean,
      _flowType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createWithdraStepTask(
      _supplier: string,
      _stepTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialize(
      _ops: string,
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    checkerStopStream(
      _receiver: string,
      _all: boolean,
      _flowType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkerwithdrawStep(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createStopStreamTimedTask(
      _supplier: string,
      _stopDateInMs: BigNumberish,
      _all: boolean,
      _flowType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createWithdraStepTask(
      _supplier: string,
      _stepTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      _ops: string,
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
