/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type YieldStruct = {
  yieldTokenIndex: BigNumberish;
  yieldInFlowRateIndex: BigNumberish;
  yieldAccrued: BigNumberish;
  yieldSnapshot: BigNumberish;
  totalYield: BigNumberish;
  protocolYield: BigNumberish;
};

export type YieldStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  yieldTokenIndex: BigNumber;
  yieldInFlowRateIndex: BigNumber;
  yieldAccrued: BigNumber;
  yieldSnapshot: BigNumber;
  totalYield: BigNumber;
  protocolYield: BigNumber;
};

export type APYStruct = { span: BigNumberish; apy: BigNumberish };

export type APYStructOutput = [BigNumber, BigNumber] & {
  span: BigNumber;
  apy: BigNumber;
};

export type PoolV1Struct = {
  id: BigNumberish;
  timestamp: BigNumberish;
  nrSuppliers: BigNumberish;
  deposit: BigNumberish;
  depositFromInFlowRate: BigNumberish;
  inFlowRate: BigNumberish;
  outFlowRate: BigNumberish;
  outFlowBuffer: BigNumberish;
  yieldObject: YieldStruct;
  apy: APYStruct;
};

export type PoolV1StructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  YieldStructOutput,
  APYStructOutput
] & {
  id: BigNumber;
  timestamp: BigNumber;
  nrSuppliers: BigNumber;
  deposit: BigNumber;
  depositFromInFlowRate: BigNumber;
  inFlowRate: BigNumber;
  outFlowRate: BigNumber;
  outFlowBuffer: BigNumber;
  yieldObject: YieldStructOutput;
  apy: APYStructOutput;
};

export type OutStreamStruct = {
  flow: BigNumberish;
  stepAmount: BigNumberish;
  streamDuration: BigNumberish;
  initTime: BigNumberish;
  minBalance: BigNumberish;
  cancelWithdrawId: BytesLike;
};

export type OutStreamStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  string
] & {
  flow: BigNumber;
  stepAmount: BigNumber;
  streamDuration: BigNumber;
  initTime: BigNumber;
  minBalance: BigNumber;
  cancelWithdrawId: string;
};

export type SupplierStruct = {
  id: BigNumberish;
  supplier: string;
  cumulatedYield: BigNumberish;
  deposit: BigNumberish;
  timestamp: BigNumberish;
  createdTimestamp: BigNumberish;
  eventId: BigNumberish;
  inStream: BigNumberish;
  outStream: OutStreamStruct;
  apy: APYStruct;
};

export type SupplierStructOutput = [
  BigNumber,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  OutStreamStructOutput,
  APYStructOutput
] & {
  id: BigNumber;
  supplier: string;
  cumulatedYield: BigNumber;
  deposit: BigNumber;
  timestamp: BigNumber;
  createdTimestamp: BigNumber;
  eventId: BigNumber;
  inStream: BigNumber;
  outStream: OutStreamStructOutput;
  apy: APYStructOutput;
};

export type PoolInternalInitializerStruct = {
  superToken: string;
  pool: string;
  poolStrategy: string;
  ops: string;
  owner: string;
};

export type PoolInternalInitializerStructOutput = [
  string,
  string,
  string,
  string,
  string
] & {
  superToken: string;
  pool: string;
  poolStrategy: string;
  ops: string;
  owner: string;
};

export interface PoolInternalV1Interface extends utils.Interface {
  functions: {
    "ETH()": FunctionFragment;
    "MIN_OUTFLOW_ALLOWED()": FunctionFragment;
    "POOL_BUFFER()": FunctionFragment;
    "PRECISSION()": FunctionFragment;
    "PROTOCOL_FEE()": FunctionFragment;
    "STEPS()": FunctionFragment;
    "SUPERFLUID_DEPOSIT()": FunctionFragment;
    "_calculateIndexes(uint256,(uint256,uint256,uint256,uint256,uint256,int96,int96,uint256,(uint256,uint256,uint256,uint256,uint256,uint256),(uint256,uint256)))": FunctionFragment;
    "_calculateYieldSupplier(address)": FunctionFragment;
    "_closeAccount()": FunctionFragment;
    "_poolUpdate()": FunctionFragment;
    "_redeemDeposit(uint256,address)": FunctionFragment;
    "_redeemFlow(int96,address)": FunctionFragment;
    "_redeemFlowStop(address)": FunctionFragment;
    "_tokensReceived(address,uint256)": FunctionFragment;
    "cancelTask(bytes32)": FunctionFragment;
    "getCodeAddress()": FunctionFragment;
    "getLastPool()": FunctionFragment;
    "getLastTimestamp()": FunctionFragment;
    "getPool(uint256)": FunctionFragment;
    "getSupplier(address)": FunctionFragment;
    "getVersion()": FunctionFragment;
    "initialize((address,address,address,address,address))": FunctionFragment;
    "lastPoolTimestamp()": FunctionFragment;
    "ops()": FunctionFragment;
    "poolByTimestamp(uint256)": FunctionFragment;
    "poolTimestampById(uint256)": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "pushedToStrategy(uint256)": FunctionFragment;
    "suppliersByAddress(address)": FunctionFragment;
    "totalYieldEarnedSupplier(address,uint256)": FunctionFragment;
    "transferSTokens(address,address,uint256)": FunctionFragment;
    "updateCode(address)": FunctionFragment;
    "updateStreamRecord(bytes,int96,address)": FunctionFragment;
    "withdrawStep(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "ETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MIN_OUTFLOW_ALLOWED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POOL_BUFFER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRECISSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "STEPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "SUPERFLUID_DEPOSIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_calculateIndexes",
    values: [BigNumberish, PoolV1Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "_calculateYieldSupplier",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_closeAccount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_poolUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_redeemDeposit",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "_redeemFlow",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "_redeemFlowStop",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_tokensReceived",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCodeAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLastPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLastTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getSupplier", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [PoolInternalInitializerStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "lastPoolTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ops", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolByTimestamp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "poolTimestampById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pushedToStrategy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "suppliersByAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalYieldEarnedSupplier",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferSTokens",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "updateCode", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateStreamRecord",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawStep",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "ETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_OUTFLOW_ALLOWED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POOL_BUFFER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PRECISSION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "STEPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SUPERFLUID_DEPOSIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_calculateIndexes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_calculateYieldSupplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_closeAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_poolUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_redeemDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_redeemFlow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_redeemFlowStop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_tokensReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCodeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSupplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVersion", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastPoolTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ops", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolByTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolTimestampById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pushedToStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "suppliersByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalYieldEarnedSupplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferSTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateCode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateStreamRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStep",
    data: BytesLike
  ): Result;

  events: {
    "CodeUpdated(bytes32,address)": EventFragment;
    "Initialized(uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CodeUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
}

export type CodeUpdatedEvent = TypedEvent<
  [string, string],
  { uuid: string; codeAddress: string }
>;

export type CodeUpdatedEventFilter = TypedEventFilter<CodeUpdatedEvent>;

export type InitializedEvent = TypedEvent<[number], { version: number }>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface PoolInternalV1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PoolInternalV1Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ETH(overrides?: CallOverrides): Promise<[string]>;

    MIN_OUTFLOW_ALLOWED(overrides?: CallOverrides): Promise<[BigNumber]>;

    POOL_BUFFER(overrides?: CallOverrides): Promise<[BigNumber]>;

    PRECISSION(overrides?: CallOverrides): Promise<[BigNumber]>;

    PROTOCOL_FEE(overrides?: CallOverrides): Promise<[BigNumber]>;

    STEPS(overrides?: CallOverrides): Promise<[number]>;

    SUPERFLUID_DEPOSIT(overrides?: CallOverrides): Promise<[BigNumber]>;

    _calculateIndexes(
      yieldPeriod: BigNumberish,
      lastPool: PoolV1Struct,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        periodYieldTokenIndex: BigNumber;
        periodYieldInFlowRateIndex: BigNumber;
      }
    >;

    _calculateYieldSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { yieldSupplier: BigNumber }>;

    _closeAccount(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _poolUpdate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _redeemDeposit(
      redeemAmount: BigNumberish,
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _redeemFlow(
      _outFlowRate: BigNumberish,
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _redeemFlowStop(
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _tokensReceived(
      from: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelTask(
      _taskId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getCodeAddress(
      overrides?: CallOverrides
    ): Promise<[string] & { codeAddress: string }>;

    getLastPool(
      overrides?: CallOverrides
    ): Promise<[PoolV1StructOutput] & { pool: PoolV1StructOutput }>;

    getLastTimestamp(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPool(
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[PoolV1StructOutput] & { pool: PoolV1StructOutput }>;

    getSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<[SupplierStructOutput] & { supplier: SupplierStructOutput }>;

    getVersion(overrides?: CallOverrides): Promise<[BigNumber]>;

    initialize(
      internalInit: PoolInternalInitializerStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lastPoolTimestamp(overrides?: CallOverrides): Promise<[BigNumber]>;

    ops(overrides?: CallOverrides): Promise<[string]>;

    poolByTimestamp(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        YieldStructOutput,
        APYStructOutput
      ] & {
        id: BigNumber;
        timestamp: BigNumber;
        nrSuppliers: BigNumber;
        deposit: BigNumber;
        depositFromInFlowRate: BigNumber;
        inFlowRate: BigNumber;
        outFlowRate: BigNumber;
        outFlowBuffer: BigNumber;
        yieldObject: YieldStructOutput;
        apy: APYStructOutput;
      }
    >;

    poolTimestampById(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    pushedToStrategy(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    suppliersByAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        OutStreamStructOutput,
        APYStructOutput
      ] & {
        id: BigNumber;
        supplier: string;
        cumulatedYield: BigNumber;
        deposit: BigNumber;
        timestamp: BigNumber;
        createdTimestamp: BigNumber;
        eventId: BigNumber;
        inStream: BigNumber;
        outStream: OutStreamStructOutput;
        apy: APYStructOutput;
      }
    >;

    totalYieldEarnedSupplier(
      _supplier: string,
      currentYieldSnapshot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { yieldSupplier: BigNumber }>;

    transferSTokens(
      _sender: string,
      _receiver: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateCode(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateStreamRecord(
      newCtx: BytesLike,
      inFlowRate: BigNumberish,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawStep(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  ETH(overrides?: CallOverrides): Promise<string>;

  MIN_OUTFLOW_ALLOWED(overrides?: CallOverrides): Promise<BigNumber>;

  POOL_BUFFER(overrides?: CallOverrides): Promise<BigNumber>;

  PRECISSION(overrides?: CallOverrides): Promise<BigNumber>;

  PROTOCOL_FEE(overrides?: CallOverrides): Promise<BigNumber>;

  STEPS(overrides?: CallOverrides): Promise<number>;

  SUPERFLUID_DEPOSIT(overrides?: CallOverrides): Promise<BigNumber>;

  _calculateIndexes(
    yieldPeriod: BigNumberish,
    lastPool: PoolV1Struct,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      periodYieldTokenIndex: BigNumber;
      periodYieldInFlowRateIndex: BigNumber;
    }
  >;

  _calculateYieldSupplier(
    _supplier: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  _closeAccount(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _poolUpdate(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _redeemDeposit(
    redeemAmount: BigNumberish,
    _supplier: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _redeemFlow(
    _outFlowRate: BigNumberish,
    _supplier: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _redeemFlowStop(
    _supplier: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _tokensReceived(
    from: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelTask(
    _taskId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getCodeAddress(overrides?: CallOverrides): Promise<string>;

  getLastPool(overrides?: CallOverrides): Promise<PoolV1StructOutput>;

  getLastTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

  getPool(
    timestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<PoolV1StructOutput>;

  getSupplier(
    _supplier: string,
    overrides?: CallOverrides
  ): Promise<SupplierStructOutput>;

  getVersion(overrides?: CallOverrides): Promise<BigNumber>;

  initialize(
    internalInit: PoolInternalInitializerStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lastPoolTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

  ops(overrides?: CallOverrides): Promise<string>;

  poolByTimestamp(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      YieldStructOutput,
      APYStructOutput
    ] & {
      id: BigNumber;
      timestamp: BigNumber;
      nrSuppliers: BigNumber;
      deposit: BigNumber;
      depositFromInFlowRate: BigNumber;
      inFlowRate: BigNumber;
      outFlowRate: BigNumber;
      outFlowBuffer: BigNumber;
      yieldObject: YieldStructOutput;
      apy: APYStructOutput;
    }
  >;

  poolTimestampById(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  pushedToStrategy(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  suppliersByAddress(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      OutStreamStructOutput,
      APYStructOutput
    ] & {
      id: BigNumber;
      supplier: string;
      cumulatedYield: BigNumber;
      deposit: BigNumber;
      timestamp: BigNumber;
      createdTimestamp: BigNumber;
      eventId: BigNumber;
      inStream: BigNumber;
      outStream: OutStreamStructOutput;
      apy: APYStructOutput;
    }
  >;

  totalYieldEarnedSupplier(
    _supplier: string,
    currentYieldSnapshot: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  transferSTokens(
    _sender: string,
    _receiver: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateCode(
    newAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateStreamRecord(
    newCtx: BytesLike,
    inFlowRate: BigNumberish,
    sender: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawStep(
    _receiver: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    ETH(overrides?: CallOverrides): Promise<string>;

    MIN_OUTFLOW_ALLOWED(overrides?: CallOverrides): Promise<BigNumber>;

    POOL_BUFFER(overrides?: CallOverrides): Promise<BigNumber>;

    PRECISSION(overrides?: CallOverrides): Promise<BigNumber>;

    PROTOCOL_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    STEPS(overrides?: CallOverrides): Promise<number>;

    SUPERFLUID_DEPOSIT(overrides?: CallOverrides): Promise<BigNumber>;

    _calculateIndexes(
      yieldPeriod: BigNumberish,
      lastPool: PoolV1Struct,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        periodYieldTokenIndex: BigNumber;
        periodYieldInFlowRateIndex: BigNumber;
      }
    >;

    _calculateYieldSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _closeAccount(overrides?: CallOverrides): Promise<void>;

    _poolUpdate(overrides?: CallOverrides): Promise<void>;

    _redeemDeposit(
      redeemAmount: BigNumberish,
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<void>;

    _redeemFlow(
      _outFlowRate: BigNumberish,
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<void>;

    _redeemFlowStop(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<void>;

    _tokensReceived(
      from: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelTask(_taskId: BytesLike, overrides?: CallOverrides): Promise<void>;

    getCodeAddress(overrides?: CallOverrides): Promise<string>;

    getLastPool(overrides?: CallOverrides): Promise<PoolV1StructOutput>;

    getLastTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    getPool(
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PoolV1StructOutput>;

    getSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<SupplierStructOutput>;

    getVersion(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      internalInit: PoolInternalInitializerStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    lastPoolTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    ops(overrides?: CallOverrides): Promise<string>;

    poolByTimestamp(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        YieldStructOutput,
        APYStructOutput
      ] & {
        id: BigNumber;
        timestamp: BigNumber;
        nrSuppliers: BigNumber;
        deposit: BigNumber;
        depositFromInFlowRate: BigNumber;
        inFlowRate: BigNumber;
        outFlowRate: BigNumber;
        outFlowBuffer: BigNumber;
        yieldObject: YieldStructOutput;
        apy: APYStructOutput;
      }
    >;

    poolTimestampById(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    pushedToStrategy(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    suppliersByAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        OutStreamStructOutput,
        APYStructOutput
      ] & {
        id: BigNumber;
        supplier: string;
        cumulatedYield: BigNumber;
        deposit: BigNumber;
        timestamp: BigNumber;
        createdTimestamp: BigNumber;
        eventId: BigNumber;
        inStream: BigNumber;
        outStream: OutStreamStructOutput;
        apy: APYStructOutput;
      }
    >;

    totalYieldEarnedSupplier(
      _supplier: string,
      currentYieldSnapshot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferSTokens(
      _sender: string,
      _receiver: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateCode(newAddress: string, overrides?: CallOverrides): Promise<void>;

    updateStreamRecord(
      newCtx: BytesLike,
      inFlowRate: BigNumberish,
      sender: string,
      overrides?: CallOverrides
    ): Promise<string>;

    withdrawStep(_receiver: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "CodeUpdated(bytes32,address)"(
      uuid?: null,
      codeAddress?: null
    ): CodeUpdatedEventFilter;
    CodeUpdated(uuid?: null, codeAddress?: null): CodeUpdatedEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;
  };

  estimateGas: {
    ETH(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_OUTFLOW_ALLOWED(overrides?: CallOverrides): Promise<BigNumber>;

    POOL_BUFFER(overrides?: CallOverrides): Promise<BigNumber>;

    PRECISSION(overrides?: CallOverrides): Promise<BigNumber>;

    PROTOCOL_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    STEPS(overrides?: CallOverrides): Promise<BigNumber>;

    SUPERFLUID_DEPOSIT(overrides?: CallOverrides): Promise<BigNumber>;

    _calculateIndexes(
      yieldPeriod: BigNumberish,
      lastPool: PoolV1Struct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _calculateYieldSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _closeAccount(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _poolUpdate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _redeemDeposit(
      redeemAmount: BigNumberish,
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _redeemFlow(
      _outFlowRate: BigNumberish,
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _redeemFlowStop(
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _tokensReceived(
      from: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelTask(
      _taskId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getCodeAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getLastPool(overrides?: CallOverrides): Promise<BigNumber>;

    getLastTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    getPool(
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVersion(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      internalInit: PoolInternalInitializerStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lastPoolTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    ops(overrides?: CallOverrides): Promise<BigNumber>;

    poolByTimestamp(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    poolTimestampById(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    pushedToStrategy(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    suppliersByAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalYieldEarnedSupplier(
      _supplier: string,
      currentYieldSnapshot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferSTokens(
      _sender: string,
      _receiver: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateCode(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateStreamRecord(
      newCtx: BytesLike,
      inFlowRate: BigNumberish,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawStep(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MIN_OUTFLOW_ALLOWED(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    POOL_BUFFER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PRECISSION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PROTOCOL_FEE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    STEPS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SUPERFLUID_DEPOSIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _calculateIndexes(
      yieldPeriod: BigNumberish,
      lastPool: PoolV1Struct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _calculateYieldSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _closeAccount(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _poolUpdate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _redeemDeposit(
      redeemAmount: BigNumberish,
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _redeemFlow(
      _outFlowRate: BigNumberish,
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _redeemFlowStop(
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _tokensReceived(
      from: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelTask(
      _taskId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getCodeAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLastPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLastTimestamp(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPool(
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVersion(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      internalInit: PoolInternalInitializerStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lastPoolTimestamp(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ops(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poolByTimestamp(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    poolTimestampById(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pushedToStrategy(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    suppliersByAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalYieldEarnedSupplier(
      _supplier: string,
      currentYieldSnapshot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferSTokens(
      _sender: string,
      _receiver: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateCode(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateStreamRecord(
      newCtx: BytesLike,
      inFlowRate: BigNumberish,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawStep(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
