/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type APYStruct = { span: BigNumberish; apy: BigNumberish };

export type APYStructOutput = [BigNumber, BigNumber] & {
  span: BigNumber;
  apy: BigNumber;
};

export type PoolV2Struct = {
  id: BigNumberish;
  timestamp: BigNumberish;
  nrSuppliers: BigNumberish;
  deposit: BigNumberish;
  depositFromInFlowRate: BigNumberish;
  inFlowRate: BigNumberish;
  outFlowRate: BigNumberish;
  outFlowBuffer: BigNumberish;
  yieldTokenIndex: BigNumberish;
  yieldInFlowRateIndex: BigNumberish;
  yieldAccrued: BigNumberish;
  yieldSnapshot: BigNumberish;
  totalYield: BigNumberish;
  apy: APYStruct;
};

export type PoolV2StructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  APYStructOutput
] & {
  id: BigNumber;
  timestamp: BigNumber;
  nrSuppliers: BigNumber;
  deposit: BigNumber;
  depositFromInFlowRate: BigNumber;
  inFlowRate: BigNumber;
  outFlowRate: BigNumber;
  outFlowBuffer: BigNumber;
  yieldTokenIndex: BigNumber;
  yieldInFlowRateIndex: BigNumber;
  yieldAccrued: BigNumber;
  yieldSnapshot: BigNumber;
  totalYield: BigNumber;
  apy: APYStructOutput;
};

export type ContextStruct = {
  appCallbackLevel: BigNumberish;
  callType: BigNumberish;
  timestamp: BigNumberish;
  msgSender: string;
  agreementSelector: BytesLike;
  userData: BytesLike;
  appCreditGranted: BigNumberish;
  appCreditWantedDeprecated: BigNumberish;
  appCreditUsed: BigNumberish;
  appAddress: string;
  appCreditToken: string;
};

export type ContextStructOutput = [
  number,
  number,
  BigNumber,
  string,
  string,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  string,
  string
] & {
  appCallbackLevel: number;
  callType: number;
  timestamp: BigNumber;
  msgSender: string;
  agreementSelector: string;
  userData: string;
  appCreditGranted: BigNumber;
  appCreditWantedDeprecated: BigNumber;
  appCreditUsed: BigNumber;
  appAddress: string;
  appCreditToken: string;
};

export type StreamStruct = { flow: BigNumberish; cancelFlowId: BytesLike };

export type StreamStructOutput = [BigNumber, string] & {
  flow: BigNumber;
  cancelFlowId: string;
};

export type OutStreamStruct = {
  flow: BigNumberish;
  cancelFlowId: BytesLike;
  stepAmount: BigNumberish;
  stepTime: BigNumberish;
  initTime: BigNumberish;
  minBalance: BigNumberish;
  cancelWithdrawId: BytesLike;
};

export type OutStreamStructOutput = [
  BigNumber,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  string
] & {
  flow: BigNumber;
  cancelFlowId: string;
  stepAmount: BigNumber;
  stepTime: BigNumber;
  initTime: BigNumber;
  minBalance: BigNumber;
  cancelWithdrawId: string;
};

export type SupplierStruct = {
  id: BigNumberish;
  supplier: string;
  cumulatedYield: BigNumberish;
  deposit: BigNumberish;
  timestamp: BigNumberish;
  createdTimestamp: BigNumberish;
  eventId: BigNumberish;
  inStream: StreamStruct;
  outStream: OutStreamStruct;
  apy: APYStruct;
};

export type SupplierStructOutput = [
  BigNumber,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  StreamStructOutput,
  OutStreamStructOutput,
  APYStructOutput
] & {
  id: BigNumber;
  supplier: string;
  cumulatedYield: BigNumber;
  deposit: BigNumber;
  timestamp: BigNumber;
  createdTimestamp: BigNumber;
  eventId: BigNumber;
  inStream: StreamStructOutput;
  outStream: OutStreamStructOutput;
  apy: APYStructOutput;
};

export interface PoolInternalV2Interface extends utils.Interface {
  functions: {
    "MIN_OUTFLOW_ALLOWED()": FunctionFragment;
    "POOL_BUFFER()": FunctionFragment;
    "PRECISSION()": FunctionFragment;
    "STEPS()": FunctionFragment;
    "SUPERFLUID_DEPOSIT()": FunctionFragment;
    "_calculateIndexes(uint256,(uint256,uint256,uint256,uint256,uint256,int96,int96,uint256,uint256,uint256,uint256,uint256,uint256,(uint256,uint256)))": FunctionFragment;
    "_calculateYieldSupplier(address)": FunctionFragment;
    "_poolUpdate()": FunctionFragment;
    "_redeemDeposit(uint256,address)": FunctionFragment;
    "_redeemFlow(int96,address)": FunctionFragment;
    "_redeemFlowStop(address)": FunctionFragment;
    "_tokensReceived(address,uint256)": FunctionFragment;
    "cancelTask(bytes32)": FunctionFragment;
    "createFlow(bytes,(uint8,uint8,uint256,address,bytes4,bytes,uint256,uint256,int256,address,address),int96,address)": FunctionFragment;
    "getLastPool()": FunctionFragment;
    "getLastTimestmap()": FunctionFragment;
    "getPool(uint256)": FunctionFragment;
    "getSupplier(address)": FunctionFragment;
    "initialize(address,address,address)": FunctionFragment;
    "lastPoolTimestamp()": FunctionFragment;
    "ops()": FunctionFragment;
    "parseLoanData(bytes)": FunctionFragment;
    "poolByTimestamp(uint256)": FunctionFragment;
    "poolTimestampById(uint256)": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "pushedToStrategy(uint256)": FunctionFragment;
    "suppliersByAddress(address)": FunctionFragment;
    "terminateFlow(bytes,address)": FunctionFragment;
    "totalYieldEarnedSupplier(address,uint256)": FunctionFragment;
    "transferSTokens(address,address,uint256)": FunctionFragment;
    "updateFlow(bytes,int96,address)": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "withdrawStep(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MIN_OUTFLOW_ALLOWED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POOL_BUFFER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRECISSION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "STEPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "SUPERFLUID_DEPOSIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_calculateIndexes",
    values: [BigNumberish, PoolV2Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "_calculateYieldSupplier",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_poolUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_redeemDeposit",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "_redeemFlow",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "_redeemFlowStop",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_tokensReceived",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createFlow",
    values: [BytesLike, ContextStruct, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLastTimestmap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getSupplier", values: [string]): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "lastPoolTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ops", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "parseLoanData",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "poolByTimestamp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "poolTimestampById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pushedToStrategy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "suppliersByAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "terminateFlow",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalYieldEarnedSupplier",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferSTokens",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFlow",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "upgradeTo", values: [string]): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawStep",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_OUTFLOW_ALLOWED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POOL_BUFFER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PRECISSION", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "STEPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SUPERFLUID_DEPOSIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_calculateIndexes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_calculateYieldSupplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_poolUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_redeemDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_redeemFlow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_redeemFlowStop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_tokensReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createFlow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLastPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastTimestmap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSupplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastPoolTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ops", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "parseLoanData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolByTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolTimestampById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pushedToStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "suppliersByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "terminateFlow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalYieldEarnedSupplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferSTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateFlow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStep",
    data: BytesLike
  ): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export type AdminChangedEvent = TypedEvent<
  [string, string],
  { previousAdmin: string; newAdmin: string }
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export type BeaconUpgradedEvent = TypedEvent<[string], { beacon: string }>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export type InitializedEvent = TypedEvent<[number], { version: number }>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export type UpgradedEvent = TypedEvent<[string], { implementation: string }>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface PoolInternalV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PoolInternalV2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MIN_OUTFLOW_ALLOWED(overrides?: CallOverrides): Promise<[BigNumber]>;

    POOL_BUFFER(overrides?: CallOverrides): Promise<[BigNumber]>;

    PRECISSION(overrides?: CallOverrides): Promise<[BigNumber]>;

    STEPS(overrides?: CallOverrides): Promise<[number]>;

    SUPERFLUID_DEPOSIT(overrides?: CallOverrides): Promise<[BigNumber]>;

    _calculateIndexes(
      yieldPeriod: BigNumberish,
      lastPool: PoolV2Struct,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        periodYieldTokenIndex: BigNumber;
        periodYieldInFlowRateIndex: BigNumber;
      }
    >;

    _calculateYieldSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { yieldSupplier: BigNumber }>;

    _poolUpdate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _redeemDeposit(
      redeemAmount: BigNumberish,
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _redeemFlow(
      _outFlowRate: BigNumberish,
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _redeemFlowStop(
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _tokensReceived(
      from: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelTask(
      _taskId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createFlow(
      newCtx: BytesLike,
      decodedContext: ContextStruct,
      inFlowRate: BigNumberish,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getLastPool(
      overrides?: CallOverrides
    ): Promise<[PoolV2StructOutput] & { pool: PoolV2StructOutput }>;

    getLastTimestmap(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPool(
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[PoolV2StructOutput] & { pool: PoolV2StructOutput }>;

    getSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<[SupplierStructOutput] & { supplier: SupplierStructOutput }>;

    initialize(
      _resolverSettings: string,
      _owner: string,
      _superToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lastPoolTimestamp(overrides?: CallOverrides): Promise<[BigNumber]>;

    ops(overrides?: CallOverrides): Promise<[string]>;

    parseLoanData(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { endSeconds: BigNumber }>;

    poolByTimestamp(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        APYStructOutput
      ] & {
        id: BigNumber;
        timestamp: BigNumber;
        nrSuppliers: BigNumber;
        deposit: BigNumber;
        depositFromInFlowRate: BigNumber;
        inFlowRate: BigNumber;
        outFlowRate: BigNumber;
        outFlowBuffer: BigNumber;
        yieldTokenIndex: BigNumber;
        yieldInFlowRateIndex: BigNumber;
        yieldAccrued: BigNumber;
        yieldSnapshot: BigNumber;
        totalYield: BigNumber;
        apy: APYStructOutput;
      }
    >;

    poolTimestampById(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    pushedToStrategy(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    suppliersByAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        StreamStructOutput,
        OutStreamStructOutput,
        APYStructOutput
      ] & {
        id: BigNumber;
        supplier: string;
        cumulatedYield: BigNumber;
        deposit: BigNumber;
        timestamp: BigNumber;
        createdTimestamp: BigNumber;
        eventId: BigNumber;
        inStream: StreamStructOutput;
        outStream: OutStreamStructOutput;
        apy: APYStructOutput;
      }
    >;

    terminateFlow(
      newCtx: BytesLike,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalYieldEarnedSupplier(
      _supplier: string,
      currentYieldSnapshot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { yieldSupplier: BigNumber }>;

    transferSTokens(
      _sender: string,
      _receiver: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateFlow(
      newCtx: BytesLike,
      inFlowRate: BigNumberish,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawStep(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  MIN_OUTFLOW_ALLOWED(overrides?: CallOverrides): Promise<BigNumber>;

  POOL_BUFFER(overrides?: CallOverrides): Promise<BigNumber>;

  PRECISSION(overrides?: CallOverrides): Promise<BigNumber>;

  STEPS(overrides?: CallOverrides): Promise<number>;

  SUPERFLUID_DEPOSIT(overrides?: CallOverrides): Promise<BigNumber>;

  _calculateIndexes(
    yieldPeriod: BigNumberish,
    lastPool: PoolV2Struct,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      periodYieldTokenIndex: BigNumber;
      periodYieldInFlowRateIndex: BigNumber;
    }
  >;

  _calculateYieldSupplier(
    _supplier: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  _poolUpdate(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _redeemDeposit(
    redeemAmount: BigNumberish,
    _supplier: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _redeemFlow(
    _outFlowRate: BigNumberish,
    _supplier: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _redeemFlowStop(
    _supplier: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _tokensReceived(
    from: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelTask(
    _taskId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createFlow(
    newCtx: BytesLike,
    decodedContext: ContextStruct,
    inFlowRate: BigNumberish,
    sender: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getLastPool(overrides?: CallOverrides): Promise<PoolV2StructOutput>;

  getLastTimestmap(overrides?: CallOverrides): Promise<BigNumber>;

  getPool(
    timestamp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<PoolV2StructOutput>;

  getSupplier(
    _supplier: string,
    overrides?: CallOverrides
  ): Promise<SupplierStructOutput>;

  initialize(
    _resolverSettings: string,
    _owner: string,
    _superToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lastPoolTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

  ops(overrides?: CallOverrides): Promise<string>;

  parseLoanData(data: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  poolByTimestamp(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      APYStructOutput
    ] & {
      id: BigNumber;
      timestamp: BigNumber;
      nrSuppliers: BigNumber;
      deposit: BigNumber;
      depositFromInFlowRate: BigNumber;
      inFlowRate: BigNumber;
      outFlowRate: BigNumber;
      outFlowBuffer: BigNumber;
      yieldTokenIndex: BigNumber;
      yieldInFlowRateIndex: BigNumber;
      yieldAccrued: BigNumber;
      yieldSnapshot: BigNumber;
      totalYield: BigNumber;
      apy: APYStructOutput;
    }
  >;

  poolTimestampById(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  pushedToStrategy(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  suppliersByAddress(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      StreamStructOutput,
      OutStreamStructOutput,
      APYStructOutput
    ] & {
      id: BigNumber;
      supplier: string;
      cumulatedYield: BigNumber;
      deposit: BigNumber;
      timestamp: BigNumber;
      createdTimestamp: BigNumber;
      eventId: BigNumber;
      inStream: StreamStructOutput;
      outStream: OutStreamStructOutput;
      apy: APYStructOutput;
    }
  >;

  terminateFlow(
    newCtx: BytesLike,
    sender: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalYieldEarnedSupplier(
    _supplier: string,
    currentYieldSnapshot: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  transferSTokens(
    _sender: string,
    _receiver: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateFlow(
    newCtx: BytesLike,
    inFlowRate: BigNumberish,
    sender: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgradeTo(
    newImplementation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: string,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawStep(
    _receiver: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    MIN_OUTFLOW_ALLOWED(overrides?: CallOverrides): Promise<BigNumber>;

    POOL_BUFFER(overrides?: CallOverrides): Promise<BigNumber>;

    PRECISSION(overrides?: CallOverrides): Promise<BigNumber>;

    STEPS(overrides?: CallOverrides): Promise<number>;

    SUPERFLUID_DEPOSIT(overrides?: CallOverrides): Promise<BigNumber>;

    _calculateIndexes(
      yieldPeriod: BigNumberish,
      lastPool: PoolV2Struct,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        periodYieldTokenIndex: BigNumber;
        periodYieldInFlowRateIndex: BigNumber;
      }
    >;

    _calculateYieldSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _poolUpdate(overrides?: CallOverrides): Promise<void>;

    _redeemDeposit(
      redeemAmount: BigNumberish,
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<void>;

    _redeemFlow(
      _outFlowRate: BigNumberish,
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<void>;

    _redeemFlowStop(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<void>;

    _tokensReceived(
      from: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelTask(_taskId: BytesLike, overrides?: CallOverrides): Promise<void>;

    createFlow(
      newCtx: BytesLike,
      decodedContext: ContextStruct,
      inFlowRate: BigNumberish,
      sender: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getLastPool(overrides?: CallOverrides): Promise<PoolV2StructOutput>;

    getLastTimestmap(overrides?: CallOverrides): Promise<BigNumber>;

    getPool(
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PoolV2StructOutput>;

    getSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<SupplierStructOutput>;

    initialize(
      _resolverSettings: string,
      _owner: string,
      _superToken: string,
      overrides?: CallOverrides
    ): Promise<void>;

    lastPoolTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    ops(overrides?: CallOverrides): Promise<string>;

    parseLoanData(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    poolByTimestamp(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        APYStructOutput
      ] & {
        id: BigNumber;
        timestamp: BigNumber;
        nrSuppliers: BigNumber;
        deposit: BigNumber;
        depositFromInFlowRate: BigNumber;
        inFlowRate: BigNumber;
        outFlowRate: BigNumber;
        outFlowBuffer: BigNumber;
        yieldTokenIndex: BigNumber;
        yieldInFlowRateIndex: BigNumber;
        yieldAccrued: BigNumber;
        yieldSnapshot: BigNumber;
        totalYield: BigNumber;
        apy: APYStructOutput;
      }
    >;

    poolTimestampById(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    pushedToStrategy(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    suppliersByAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        StreamStructOutput,
        OutStreamStructOutput,
        APYStructOutput
      ] & {
        id: BigNumber;
        supplier: string;
        cumulatedYield: BigNumber;
        deposit: BigNumber;
        timestamp: BigNumber;
        createdTimestamp: BigNumber;
        eventId: BigNumber;
        inStream: StreamStructOutput;
        outStream: OutStreamStructOutput;
        apy: APYStructOutput;
      }
    >;

    terminateFlow(
      newCtx: BytesLike,
      sender: string,
      overrides?: CallOverrides
    ): Promise<string>;

    totalYieldEarnedSupplier(
      _supplier: string,
      currentYieldSnapshot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferSTokens(
      _sender: string,
      _receiver: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateFlow(
      newCtx: BytesLike,
      inFlowRate: BigNumberish,
      sender: string,
      overrides?: CallOverrides
    ): Promise<string>;

    upgradeTo(
      newImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawStep(_receiver: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: string | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(beacon?: string | null): BeaconUpgradedEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "Upgraded(address)"(implementation?: string | null): UpgradedEventFilter;
    Upgraded(implementation?: string | null): UpgradedEventFilter;
  };

  estimateGas: {
    MIN_OUTFLOW_ALLOWED(overrides?: CallOverrides): Promise<BigNumber>;

    POOL_BUFFER(overrides?: CallOverrides): Promise<BigNumber>;

    PRECISSION(overrides?: CallOverrides): Promise<BigNumber>;

    STEPS(overrides?: CallOverrides): Promise<BigNumber>;

    SUPERFLUID_DEPOSIT(overrides?: CallOverrides): Promise<BigNumber>;

    _calculateIndexes(
      yieldPeriod: BigNumberish,
      lastPool: PoolV2Struct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _calculateYieldSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _poolUpdate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _redeemDeposit(
      redeemAmount: BigNumberish,
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _redeemFlow(
      _outFlowRate: BigNumberish,
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _redeemFlowStop(
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _tokensReceived(
      from: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelTask(
      _taskId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createFlow(
      newCtx: BytesLike,
      decodedContext: ContextStruct,
      inFlowRate: BigNumberish,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getLastPool(overrides?: CallOverrides): Promise<BigNumber>;

    getLastTimestmap(overrides?: CallOverrides): Promise<BigNumber>;

    getPool(
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _resolverSettings: string,
      _owner: string,
      _superToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lastPoolTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    ops(overrides?: CallOverrides): Promise<BigNumber>;

    parseLoanData(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    poolByTimestamp(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    poolTimestampById(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    pushedToStrategy(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    suppliersByAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    terminateFlow(
      newCtx: BytesLike,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalYieldEarnedSupplier(
      _supplier: string,
      currentYieldSnapshot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferSTokens(
      _sender: string,
      _receiver: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateFlow(
      newCtx: BytesLike,
      inFlowRate: BigNumberish,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawStep(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MIN_OUTFLOW_ALLOWED(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    POOL_BUFFER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PRECISSION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    STEPS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SUPERFLUID_DEPOSIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _calculateIndexes(
      yieldPeriod: BigNumberish,
      lastPool: PoolV2Struct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _calculateYieldSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _poolUpdate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _redeemDeposit(
      redeemAmount: BigNumberish,
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _redeemFlow(
      _outFlowRate: BigNumberish,
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _redeemFlowStop(
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _tokensReceived(
      from: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelTask(
      _taskId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createFlow(
      newCtx: BytesLike,
      decodedContext: ContextStruct,
      inFlowRate: BigNumberish,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getLastPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLastTimestmap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPool(
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _resolverSettings: string,
      _owner: string,
      _superToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lastPoolTimestamp(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ops(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    parseLoanData(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    poolByTimestamp(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    poolTimestampById(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pushedToStrategy(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    suppliersByAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    terminateFlow(
      newCtx: BytesLike,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalYieldEarnedSupplier(
      _supplier: string,
      currentYieldSnapshot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferSTokens(
      _sender: string,
      _receiver: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateFlow(
      newCtx: BytesLike,
      inFlowRate: BigNumberish,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawStep(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
