/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type YieldStruct = {
  yieldTokenIndex: BigNumberish;
  yieldInFlowRateIndex: BigNumberish;
  yieldOutFlowRateIndex: BigNumberish;
  yieldAccrued: BigNumberish;
  yieldSnapshot: BigNumberish;
  totalYield: BigNumberish;
  protocolYield: BigNumberish;
};

export type YieldStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  yieldTokenIndex: BigNumber;
  yieldInFlowRateIndex: BigNumber;
  yieldOutFlowRateIndex: BigNumber;
  yieldAccrued: BigNumber;
  yieldSnapshot: BigNumber;
  totalYield: BigNumber;
  protocolYield: BigNumber;
};

export type APYStruct = { span: BigNumberish; apy: BigNumberish };

export type APYStructOutput = [BigNumber, BigNumber] & {
  span: BigNumber;
  apy: BigNumber;
};

export type PoolV1Struct = {
  id: BigNumberish;
  timestamp: BigNumberish;
  nrSuppliers: BigNumberish;
  deposit: BigNumberish;
  depositFromInFlowRate: BigNumberish;
  depositFromOutFlowRate: BigNumberish;
  inFlowRate: BigNumberish;
  outFlowRate: BigNumberish;
  outFlowBuffer: BigNumberish;
  yieldObject: YieldStruct;
  apy: APYStruct;
};

export type PoolV1StructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  YieldStructOutput,
  APYStructOutput
] & {
  id: BigNumber;
  timestamp: BigNumber;
  nrSuppliers: BigNumber;
  deposit: BigNumber;
  depositFromInFlowRate: BigNumber;
  depositFromOutFlowRate: BigNumber;
  inFlowRate: BigNumber;
  outFlowRate: BigNumber;
  outFlowBuffer: BigNumber;
  yieldObject: YieldStructOutput;
  apy: APYStructOutput;
};

export type OutStreamStruct = {
  flow: BigNumberish;
  streamDuration: BigNumberish;
  streamInit: BigNumberish;
  cancelWithdrawId: BytesLike;
};

export type OutStreamStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  string
] & {
  flow: BigNumber;
  streamDuration: BigNumber;
  streamInit: BigNumber;
  cancelWithdrawId: string;
};

export interface PoolInternalV1Interface extends utils.Interface {
  functions: {
    "BALANCE_TRIGGER_TIME()": FunctionFragment;
    "DEPOSIT_TRIGGER_AMOUNT()": FunctionFragment;
    "ETH()": FunctionFragment;
    "MIN_OUTFLOW_ALLOWED()": FunctionFragment;
    "POOL_BUFFER()": FunctionFragment;
    "PRECISSION()": FunctionFragment;
    "PROTOCOL_FEE()": FunctionFragment;
    "SUPERFLUID_DEPOSIT()": FunctionFragment;
    "_balanceTreasury()": FunctionFragment;
    "_calculateIndexes(uint256,(uint256,uint256,uint256,uint256,uint256,uint256,int96,int96,uint256,(uint256,uint256,uint256,uint256,uint256,uint256,uint256),(uint256,uint256)))": FunctionFragment;
    "_calculateYieldSupplier(address)": FunctionFragment;
    "_cfaLib()": FunctionFragment;
    "_closeAccount()": FunctionFragment;
    "_createBalanceTreasuryTask()": FunctionFragment;
    "_poolUpdate()": FunctionFragment;
    "_redeemDeposit(address,uint256)": FunctionFragment;
    "_redeemFlow(address,int96)": FunctionFragment;
    "_redeemFlowStop(address)": FunctionFragment;
    "_tokensReceived(address,uint256)": FunctionFragment;
    "_updateSupplierFlow(address,int96,int96,bytes)": FunctionFragment;
    "balanceTreasuryTask()": FunctionFragment;
    "cancelTask(bytes32)": FunctionFragment;
    "cfa()": FunctionFragment;
    "closeStreamFlow(address)": FunctionFragment;
    "gelato()": FunctionFragment;
    "getVersion()": FunctionFragment;
    "host()": FunctionFragment;
    "lastExecution()": FunctionFragment;
    "lastPoolTimestamp()": FunctionFragment;
    "ops()": FunctionFragment;
    "owner()": FunctionFragment;
    "poolByTimestamp(uint256)": FunctionFragment;
    "poolFactory()": FunctionFragment;
    "poolId()": FunctionFragment;
    "poolInternal()": FunctionFragment;
    "poolStrategy()": FunctionFragment;
    "pushedToStrategy(uint256)": FunctionFragment;
    "supplierId()": FunctionFragment;
    "suppliersByAddress(address)": FunctionFragment;
    "totalYieldEarnedSupplier(address,uint256)": FunctionFragment;
    "transferSTokens(address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "BALANCE_TRIGGER_TIME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEPOSIT_TRIGGER_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MIN_OUTFLOW_ALLOWED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POOL_BUFFER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRECISSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUPERFLUID_DEPOSIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_balanceTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_calculateIndexes",
    values: [BigNumberish, PoolV1Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "_calculateYieldSupplier",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "_cfaLib", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "_closeAccount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_createBalanceTreasuryTask",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_poolUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_redeemDeposit",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_redeemFlow",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_redeemFlowStop",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "_tokensReceived",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_updateSupplierFlow",
    values: [string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceTreasuryTask",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "cfa", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "closeStreamFlow",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "gelato", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getVersion",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "host", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastExecution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastPoolTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ops", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolByTimestamp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "poolFactory",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "poolId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolInternal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "poolStrategy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pushedToStrategy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supplierId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "suppliersByAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalYieldEarnedSupplier",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferSTokens",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BALANCE_TRIGGER_TIME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEPOSIT_TRIGGER_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_OUTFLOW_ALLOWED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POOL_BUFFER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PRECISSION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUPERFLUID_DEPOSIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_balanceTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_calculateIndexes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_calculateYieldSupplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_cfaLib", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_closeAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_createBalanceTreasuryTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_poolUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_redeemDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_redeemFlow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_redeemFlowStop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_tokensReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_updateSupplierFlow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balanceTreasuryTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cfa", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeStreamFlow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gelato", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVersion", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "host", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPoolTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ops", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolByTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolInternal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pushedToStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "supplierId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "suppliersByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalYieldEarnedSupplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferSTokens",
    data: BytesLike
  ): Result;

  events: {};
}

export interface PoolInternalV1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PoolInternalV1Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BALANCE_TRIGGER_TIME(overrides?: CallOverrides): Promise<[BigNumber]>;

    DEPOSIT_TRIGGER_AMOUNT(overrides?: CallOverrides): Promise<[BigNumber]>;

    ETH(overrides?: CallOverrides): Promise<[string]>;

    MIN_OUTFLOW_ALLOWED(overrides?: CallOverrides): Promise<[BigNumber]>;

    POOL_BUFFER(overrides?: CallOverrides): Promise<[BigNumber]>;

    PRECISSION(overrides?: CallOverrides): Promise<[BigNumber]>;

    PROTOCOL_FEE(overrides?: CallOverrides): Promise<[BigNumber]>;

    SUPERFLUID_DEPOSIT(overrides?: CallOverrides): Promise<[BigNumber]>;

    _balanceTreasury(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _calculateIndexes(
      yieldPeriod: BigNumberish,
      lastPool: PoolV1Struct,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        periodYieldTokenIndex: BigNumber;
        periodYieldInFlowRateIndex: BigNumber;
        periodYieldOutFlowRateIndex: BigNumber;
      }
    >;

    _calculateYieldSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { yieldSupplier: BigNumber }>;

    _cfaLib(
      overrides?: CallOverrides
    ): Promise<[string, string] & { host: string; cfa: string }>;

    _closeAccount(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _createBalanceTreasuryTask(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _poolUpdate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _redeemDeposit(
      _supplier: string,
      redeemAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _redeemFlow(
      _supplier: string,
      _outFlowRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _redeemFlowStop(
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _tokensReceived(
      _supplier: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    _updateSupplierFlow(
      _supplier: string,
      inFlow: BigNumberish,
      outFlow: BigNumberish,
      _ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    balanceTreasuryTask(overrides?: CallOverrides): Promise<[string]>;

    cancelTask(
      _taskId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cfa(overrides?: CallOverrides): Promise<[string]>;

    closeStreamFlow(
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    gelato(overrides?: CallOverrides): Promise<[string]>;

    getVersion(overrides?: CallOverrides): Promise<[BigNumber]>;

    host(overrides?: CallOverrides): Promise<[string]>;

    lastExecution(overrides?: CallOverrides): Promise<[BigNumber]>;

    lastPoolTimestamp(overrides?: CallOverrides): Promise<[BigNumber]>;

    ops(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    poolByTimestamp(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        YieldStructOutput,
        APYStructOutput
      ] & {
        id: BigNumber;
        timestamp: BigNumber;
        nrSuppliers: BigNumber;
        deposit: BigNumber;
        depositFromInFlowRate: BigNumber;
        depositFromOutFlowRate: BigNumber;
        inFlowRate: BigNumber;
        outFlowRate: BigNumber;
        outFlowBuffer: BigNumber;
        yieldObject: YieldStructOutput;
        apy: APYStructOutput;
      }
    >;

    poolFactory(overrides?: CallOverrides): Promise<[string]>;

    poolId(overrides?: CallOverrides): Promise<[BigNumber]>;

    poolInternal(overrides?: CallOverrides): Promise<[string]>;

    poolStrategy(overrides?: CallOverrides): Promise<[string]>;

    pushedToStrategy(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supplierId(overrides?: CallOverrides): Promise<[BigNumber]>;

    suppliersByAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        OutStreamStructOutput,
        APYStructOutput
      ] & {
        id: BigNumber;
        supplier: string;
        cumulatedYield: BigNumber;
        deposit: BigNumber;
        timestamp: BigNumber;
        createdTimestamp: BigNumber;
        eventId: BigNumber;
        inStream: BigNumber;
        outStream: OutStreamStructOutput;
        apy: APYStructOutput;
      }
    >;

    totalYieldEarnedSupplier(
      _supplier: string,
      currentYieldSnapshot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { yieldSupplier: BigNumber }>;

    transferSTokens(
      _sender: string,
      _receiver: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  BALANCE_TRIGGER_TIME(overrides?: CallOverrides): Promise<BigNumber>;

  DEPOSIT_TRIGGER_AMOUNT(overrides?: CallOverrides): Promise<BigNumber>;

  ETH(overrides?: CallOverrides): Promise<string>;

  MIN_OUTFLOW_ALLOWED(overrides?: CallOverrides): Promise<BigNumber>;

  POOL_BUFFER(overrides?: CallOverrides): Promise<BigNumber>;

  PRECISSION(overrides?: CallOverrides): Promise<BigNumber>;

  PROTOCOL_FEE(overrides?: CallOverrides): Promise<BigNumber>;

  SUPERFLUID_DEPOSIT(overrides?: CallOverrides): Promise<BigNumber>;

  _balanceTreasury(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _calculateIndexes(
    yieldPeriod: BigNumberish,
    lastPool: PoolV1Struct,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      periodYieldTokenIndex: BigNumber;
      periodYieldInFlowRateIndex: BigNumber;
      periodYieldOutFlowRateIndex: BigNumber;
    }
  >;

  _calculateYieldSupplier(
    _supplier: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  _cfaLib(
    overrides?: CallOverrides
  ): Promise<[string, string] & { host: string; cfa: string }>;

  _closeAccount(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _createBalanceTreasuryTask(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _poolUpdate(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _redeemDeposit(
    _supplier: string,
    redeemAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _redeemFlow(
    _supplier: string,
    _outFlowRate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _redeemFlowStop(
    _supplier: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _tokensReceived(
    _supplier: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  _updateSupplierFlow(
    _supplier: string,
    inFlow: BigNumberish,
    outFlow: BigNumberish,
    _ctx: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  balanceTreasuryTask(overrides?: CallOverrides): Promise<string>;

  cancelTask(
    _taskId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cfa(overrides?: CallOverrides): Promise<string>;

  closeStreamFlow(
    _supplier: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  gelato(overrides?: CallOverrides): Promise<string>;

  getVersion(overrides?: CallOverrides): Promise<BigNumber>;

  host(overrides?: CallOverrides): Promise<string>;

  lastExecution(overrides?: CallOverrides): Promise<BigNumber>;

  lastPoolTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

  ops(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  poolByTimestamp(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      YieldStructOutput,
      APYStructOutput
    ] & {
      id: BigNumber;
      timestamp: BigNumber;
      nrSuppliers: BigNumber;
      deposit: BigNumber;
      depositFromInFlowRate: BigNumber;
      depositFromOutFlowRate: BigNumber;
      inFlowRate: BigNumber;
      outFlowRate: BigNumber;
      outFlowBuffer: BigNumber;
      yieldObject: YieldStructOutput;
      apy: APYStructOutput;
    }
  >;

  poolFactory(overrides?: CallOverrides): Promise<string>;

  poolId(overrides?: CallOverrides): Promise<BigNumber>;

  poolInternal(overrides?: CallOverrides): Promise<string>;

  poolStrategy(overrides?: CallOverrides): Promise<string>;

  pushedToStrategy(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supplierId(overrides?: CallOverrides): Promise<BigNumber>;

  suppliersByAddress(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      OutStreamStructOutput,
      APYStructOutput
    ] & {
      id: BigNumber;
      supplier: string;
      cumulatedYield: BigNumber;
      deposit: BigNumber;
      timestamp: BigNumber;
      createdTimestamp: BigNumber;
      eventId: BigNumber;
      inStream: BigNumber;
      outStream: OutStreamStructOutput;
      apy: APYStructOutput;
    }
  >;

  totalYieldEarnedSupplier(
    _supplier: string,
    currentYieldSnapshot: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  transferSTokens(
    _sender: string,
    _receiver: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    BALANCE_TRIGGER_TIME(overrides?: CallOverrides): Promise<BigNumber>;

    DEPOSIT_TRIGGER_AMOUNT(overrides?: CallOverrides): Promise<BigNumber>;

    ETH(overrides?: CallOverrides): Promise<string>;

    MIN_OUTFLOW_ALLOWED(overrides?: CallOverrides): Promise<BigNumber>;

    POOL_BUFFER(overrides?: CallOverrides): Promise<BigNumber>;

    PRECISSION(overrides?: CallOverrides): Promise<BigNumber>;

    PROTOCOL_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    SUPERFLUID_DEPOSIT(overrides?: CallOverrides): Promise<BigNumber>;

    _balanceTreasury(overrides?: CallOverrides): Promise<void>;

    _calculateIndexes(
      yieldPeriod: BigNumberish,
      lastPool: PoolV1Struct,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        periodYieldTokenIndex: BigNumber;
        periodYieldInFlowRateIndex: BigNumber;
        periodYieldOutFlowRateIndex: BigNumber;
      }
    >;

    _calculateYieldSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _cfaLib(
      overrides?: CallOverrides
    ): Promise<[string, string] & { host: string; cfa: string }>;

    _closeAccount(overrides?: CallOverrides): Promise<void>;

    _createBalanceTreasuryTask(overrides?: CallOverrides): Promise<string>;

    _poolUpdate(overrides?: CallOverrides): Promise<void>;

    _redeemDeposit(
      _supplier: string,
      redeemAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    _redeemFlow(
      _supplier: string,
      _outFlowRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    _redeemFlowStop(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<void>;

    _tokensReceived(
      _supplier: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    _updateSupplierFlow(
      _supplier: string,
      inFlow: BigNumberish,
      outFlow: BigNumberish,
      _ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    balanceTreasuryTask(overrides?: CallOverrides): Promise<string>;

    cancelTask(_taskId: BytesLike, overrides?: CallOverrides): Promise<void>;

    cfa(overrides?: CallOverrides): Promise<string>;

    closeStreamFlow(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<void>;

    gelato(overrides?: CallOverrides): Promise<string>;

    getVersion(overrides?: CallOverrides): Promise<BigNumber>;

    host(overrides?: CallOverrides): Promise<string>;

    lastExecution(overrides?: CallOverrides): Promise<BigNumber>;

    lastPoolTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    ops(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    poolByTimestamp(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        YieldStructOutput,
        APYStructOutput
      ] & {
        id: BigNumber;
        timestamp: BigNumber;
        nrSuppliers: BigNumber;
        deposit: BigNumber;
        depositFromInFlowRate: BigNumber;
        depositFromOutFlowRate: BigNumber;
        inFlowRate: BigNumber;
        outFlowRate: BigNumber;
        outFlowBuffer: BigNumber;
        yieldObject: YieldStructOutput;
        apy: APYStructOutput;
      }
    >;

    poolFactory(overrides?: CallOverrides): Promise<string>;

    poolId(overrides?: CallOverrides): Promise<BigNumber>;

    poolInternal(overrides?: CallOverrides): Promise<string>;

    poolStrategy(overrides?: CallOverrides): Promise<string>;

    pushedToStrategy(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    supplierId(overrides?: CallOverrides): Promise<BigNumber>;

    suppliersByAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        OutStreamStructOutput,
        APYStructOutput
      ] & {
        id: BigNumber;
        supplier: string;
        cumulatedYield: BigNumber;
        deposit: BigNumber;
        timestamp: BigNumber;
        createdTimestamp: BigNumber;
        eventId: BigNumber;
        inStream: BigNumber;
        outStream: OutStreamStructOutput;
        apy: APYStructOutput;
      }
    >;

    totalYieldEarnedSupplier(
      _supplier: string,
      currentYieldSnapshot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferSTokens(
      _sender: string,
      _receiver: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    BALANCE_TRIGGER_TIME(overrides?: CallOverrides): Promise<BigNumber>;

    DEPOSIT_TRIGGER_AMOUNT(overrides?: CallOverrides): Promise<BigNumber>;

    ETH(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_OUTFLOW_ALLOWED(overrides?: CallOverrides): Promise<BigNumber>;

    POOL_BUFFER(overrides?: CallOverrides): Promise<BigNumber>;

    PRECISSION(overrides?: CallOverrides): Promise<BigNumber>;

    PROTOCOL_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    SUPERFLUID_DEPOSIT(overrides?: CallOverrides): Promise<BigNumber>;

    _balanceTreasury(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _calculateIndexes(
      yieldPeriod: BigNumberish,
      lastPool: PoolV1Struct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _calculateYieldSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _cfaLib(overrides?: CallOverrides): Promise<BigNumber>;

    _closeAccount(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _createBalanceTreasuryTask(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _poolUpdate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _redeemDeposit(
      _supplier: string,
      redeemAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _redeemFlow(
      _supplier: string,
      _outFlowRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _redeemFlowStop(
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _tokensReceived(
      _supplier: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    _updateSupplierFlow(
      _supplier: string,
      inFlow: BigNumberish,
      outFlow: BigNumberish,
      _ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    balanceTreasuryTask(overrides?: CallOverrides): Promise<BigNumber>;

    cancelTask(
      _taskId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cfa(overrides?: CallOverrides): Promise<BigNumber>;

    closeStreamFlow(
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    gelato(overrides?: CallOverrides): Promise<BigNumber>;

    getVersion(overrides?: CallOverrides): Promise<BigNumber>;

    host(overrides?: CallOverrides): Promise<BigNumber>;

    lastExecution(overrides?: CallOverrides): Promise<BigNumber>;

    lastPoolTimestamp(overrides?: CallOverrides): Promise<BigNumber>;

    ops(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    poolByTimestamp(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    poolFactory(overrides?: CallOverrides): Promise<BigNumber>;

    poolId(overrides?: CallOverrides): Promise<BigNumber>;

    poolInternal(overrides?: CallOverrides): Promise<BigNumber>;

    poolStrategy(overrides?: CallOverrides): Promise<BigNumber>;

    pushedToStrategy(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supplierId(overrides?: CallOverrides): Promise<BigNumber>;

    suppliersByAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalYieldEarnedSupplier(
      _supplier: string,
      currentYieldSnapshot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferSTokens(
      _sender: string,
      _receiver: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BALANCE_TRIGGER_TIME(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEPOSIT_TRIGGER_AMOUNT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MIN_OUTFLOW_ALLOWED(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    POOL_BUFFER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PRECISSION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PROTOCOL_FEE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SUPERFLUID_DEPOSIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _balanceTreasury(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _calculateIndexes(
      yieldPeriod: BigNumberish,
      lastPool: PoolV1Struct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _calculateYieldSupplier(
      _supplier: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _cfaLib(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _closeAccount(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _createBalanceTreasuryTask(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _poolUpdate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _redeemDeposit(
      _supplier: string,
      redeemAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _redeemFlow(
      _supplier: string,
      _outFlowRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _redeemFlowStop(
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _tokensReceived(
      _supplier: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    _updateSupplierFlow(
      _supplier: string,
      inFlow: BigNumberish,
      outFlow: BigNumberish,
      _ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    balanceTreasuryTask(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelTask(
      _taskId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cfa(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    closeStreamFlow(
      _supplier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    gelato(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getVersion(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    host(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastExecution(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastPoolTimestamp(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ops(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poolByTimestamp(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    poolFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poolId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poolInternal(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poolStrategy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pushedToStrategy(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supplierId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    suppliersByAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalYieldEarnedSupplier(
      _supplier: string,
      currentYieldSnapshot: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferSTokens(
      _sender: string,
      _receiver: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
