/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type ResolverSettingsInitilizerStruct = {
  _poolStrategy: string;
  _gelatoTaks: string;
  _gelatoOps: string;
  _poolInternal: string;
};

export type ResolverSettingsInitilizerStructOutput = [
  string,
  string,
  string,
  string
] & {
  _poolStrategy: string;
  _gelatoTaks: string;
  _gelatoOps: string;
  _poolInternal: string;
};

export interface ResolverSettingsV2Interface extends utils.Interface {
  functions: {
    "DEPOSIT_TRIGGER_AMOUNT()": FunctionFragment;
    "DEPOSIT_TRIGGER_TIME()": FunctionFragment;
    "ETH()": FunctionFragment;
    "MIN_OUTFLOW_ALLOWED()": FunctionFragment;
    "POOL_BUFFER()": FunctionFragment;
    "PRECISSION()": FunctionFragment;
    "STEPS()": FunctionFragment;
    "SUPERFLUID_DEPOSIT()": FunctionFragment;
    "getGelatoOps()": FunctionFragment;
    "getGelatoTasks()": FunctionFragment;
    "getPool()": FunctionFragment;
    "getPoolBuffer()": FunctionFragment;
    "getPoolInternal()": FunctionFragment;
    "getPoolStrategy()": FunctionFragment;
    "getPrecission()": FunctionFragment;
    "getSToken()": FunctionFragment;
    "getSteps()": FunctionFragment;
    "getSuperfluidDeposit()": FunctionFragment;
    "initialize((address,address,address,address),address,address)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setPoolBuffer(uint256)": FunctionFragment;
    "setPrecission(uint256)": FunctionFragment;
    "setSteps(uint8)": FunctionFragment;
    "setSuperfluidDeposit(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DEPOSIT_TRIGGER_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEPOSIT_TRIGGER_TIME",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MIN_OUTFLOW_ALLOWED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "POOL_BUFFER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRECISSION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "STEPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "SUPERFLUID_DEPOSIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGelatoOps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGelatoTasks",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getPool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getPoolBuffer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolInternal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolStrategy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPrecission",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getSToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "getSteps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSuperfluidDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [ResolverSettingsInitilizerStruct, string, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolBuffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrecission",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSteps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSuperfluidDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEPOSIT_TRIGGER_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEPOSIT_TRIGGER_TIME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_OUTFLOW_ALLOWED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "POOL_BUFFER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PRECISSION", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "STEPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SUPERFLUID_DEPOSIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGelatoOps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGelatoTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolBuffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolInternal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPrecission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSteps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSuperfluidDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPoolBuffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPrecission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSteps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSuperfluidDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type InitializedEvent = TypedEvent<[number], { version: number }>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface ResolverSettingsV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ResolverSettingsV2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DEPOSIT_TRIGGER_AMOUNT(overrides?: CallOverrides): Promise<[BigNumber]>;

    DEPOSIT_TRIGGER_TIME(overrides?: CallOverrides): Promise<[BigNumber]>;

    ETH(overrides?: CallOverrides): Promise<[string]>;

    MIN_OUTFLOW_ALLOWED(overrides?: CallOverrides): Promise<[BigNumber]>;

    POOL_BUFFER(overrides?: CallOverrides): Promise<[BigNumber]>;

    PRECISSION(overrides?: CallOverrides): Promise<[BigNumber]>;

    STEPS(overrides?: CallOverrides): Promise<[number]>;

    SUPERFLUID_DEPOSIT(overrides?: CallOverrides): Promise<[BigNumber]>;

    getGelatoOps(overrides?: CallOverrides): Promise<[string]>;

    getGelatoTasks(overrides?: CallOverrides): Promise<[string]>;

    getPool(overrides?: CallOverrides): Promise<[string]>;

    getPoolBuffer(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPoolInternal(overrides?: CallOverrides): Promise<[string]>;

    getPoolStrategy(overrides?: CallOverrides): Promise<[string]>;

    getPrecission(overrides?: CallOverrides): Promise<[BigNumber]>;

    getSToken(overrides?: CallOverrides): Promise<[string]>;

    getSteps(overrides?: CallOverrides): Promise<[number]>;

    getSuperfluidDeposit(overrides?: CallOverrides): Promise<[BigNumber]>;

    initialize(
      resolverSettingsInitilizer: ResolverSettingsInitilizerStruct,
      _pool: string,
      _sToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPoolBuffer(
      _poolBuffer: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPrecission(
      _precission: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSteps(
      _steps: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSuperfluidDeposit(
      _superfluidDeposit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  DEPOSIT_TRIGGER_AMOUNT(overrides?: CallOverrides): Promise<BigNumber>;

  DEPOSIT_TRIGGER_TIME(overrides?: CallOverrides): Promise<BigNumber>;

  ETH(overrides?: CallOverrides): Promise<string>;

  MIN_OUTFLOW_ALLOWED(overrides?: CallOverrides): Promise<BigNumber>;

  POOL_BUFFER(overrides?: CallOverrides): Promise<BigNumber>;

  PRECISSION(overrides?: CallOverrides): Promise<BigNumber>;

  STEPS(overrides?: CallOverrides): Promise<number>;

  SUPERFLUID_DEPOSIT(overrides?: CallOverrides): Promise<BigNumber>;

  getGelatoOps(overrides?: CallOverrides): Promise<string>;

  getGelatoTasks(overrides?: CallOverrides): Promise<string>;

  getPool(overrides?: CallOverrides): Promise<string>;

  getPoolBuffer(overrides?: CallOverrides): Promise<BigNumber>;

  getPoolInternal(overrides?: CallOverrides): Promise<string>;

  getPoolStrategy(overrides?: CallOverrides): Promise<string>;

  getPrecission(overrides?: CallOverrides): Promise<BigNumber>;

  getSToken(overrides?: CallOverrides): Promise<string>;

  getSteps(overrides?: CallOverrides): Promise<number>;

  getSuperfluidDeposit(overrides?: CallOverrides): Promise<BigNumber>;

  initialize(
    resolverSettingsInitilizer: ResolverSettingsInitilizerStruct,
    _pool: string,
    _sToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPoolBuffer(
    _poolBuffer: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPrecission(
    _precission: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSteps(
    _steps: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSuperfluidDeposit(
    _superfluidDeposit: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DEPOSIT_TRIGGER_AMOUNT(overrides?: CallOverrides): Promise<BigNumber>;

    DEPOSIT_TRIGGER_TIME(overrides?: CallOverrides): Promise<BigNumber>;

    ETH(overrides?: CallOverrides): Promise<string>;

    MIN_OUTFLOW_ALLOWED(overrides?: CallOverrides): Promise<BigNumber>;

    POOL_BUFFER(overrides?: CallOverrides): Promise<BigNumber>;

    PRECISSION(overrides?: CallOverrides): Promise<BigNumber>;

    STEPS(overrides?: CallOverrides): Promise<number>;

    SUPERFLUID_DEPOSIT(overrides?: CallOverrides): Promise<BigNumber>;

    getGelatoOps(overrides?: CallOverrides): Promise<string>;

    getGelatoTasks(overrides?: CallOverrides): Promise<string>;

    getPool(overrides?: CallOverrides): Promise<string>;

    getPoolBuffer(overrides?: CallOverrides): Promise<BigNumber>;

    getPoolInternal(overrides?: CallOverrides): Promise<string>;

    getPoolStrategy(overrides?: CallOverrides): Promise<string>;

    getPrecission(overrides?: CallOverrides): Promise<BigNumber>;

    getSToken(overrides?: CallOverrides): Promise<string>;

    getSteps(overrides?: CallOverrides): Promise<number>;

    getSuperfluidDeposit(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      resolverSettingsInitilizer: ResolverSettingsInitilizerStruct,
      _pool: string,
      _sToken: string,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setPoolBuffer(
      _poolBuffer: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setPrecission(
      _precission: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setSteps(_steps: BigNumberish, overrides?: CallOverrides): Promise<void>;

    setSuperfluidDeposit(
      _superfluidDeposit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    DEPOSIT_TRIGGER_AMOUNT(overrides?: CallOverrides): Promise<BigNumber>;

    DEPOSIT_TRIGGER_TIME(overrides?: CallOverrides): Promise<BigNumber>;

    ETH(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_OUTFLOW_ALLOWED(overrides?: CallOverrides): Promise<BigNumber>;

    POOL_BUFFER(overrides?: CallOverrides): Promise<BigNumber>;

    PRECISSION(overrides?: CallOverrides): Promise<BigNumber>;

    STEPS(overrides?: CallOverrides): Promise<BigNumber>;

    SUPERFLUID_DEPOSIT(overrides?: CallOverrides): Promise<BigNumber>;

    getGelatoOps(overrides?: CallOverrides): Promise<BigNumber>;

    getGelatoTasks(overrides?: CallOverrides): Promise<BigNumber>;

    getPool(overrides?: CallOverrides): Promise<BigNumber>;

    getPoolBuffer(overrides?: CallOverrides): Promise<BigNumber>;

    getPoolInternal(overrides?: CallOverrides): Promise<BigNumber>;

    getPoolStrategy(overrides?: CallOverrides): Promise<BigNumber>;

    getPrecission(overrides?: CallOverrides): Promise<BigNumber>;

    getSToken(overrides?: CallOverrides): Promise<BigNumber>;

    getSteps(overrides?: CallOverrides): Promise<BigNumber>;

    getSuperfluidDeposit(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      resolverSettingsInitilizer: ResolverSettingsInitilizerStruct,
      _pool: string,
      _sToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPoolBuffer(
      _poolBuffer: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPrecission(
      _precission: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSteps(
      _steps: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSuperfluidDeposit(
      _superfluidDeposit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEPOSIT_TRIGGER_AMOUNT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEPOSIT_TRIGGER_TIME(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MIN_OUTFLOW_ALLOWED(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    POOL_BUFFER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PRECISSION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    STEPS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SUPERFLUID_DEPOSIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGelatoOps(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getGelatoTasks(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPoolBuffer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPoolInternal(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPoolStrategy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPrecission(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSteps(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSuperfluidDeposit(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      resolverSettingsInitilizer: ResolverSettingsInitilizerStruct,
      _pool: string,
      _sToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPoolBuffer(
      _poolBuffer: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPrecission(
      _precission: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSteps(
      _steps: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSuperfluidDeposit(
      _superfluidDeposit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
